import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const { chromium } = await import(process.env.KACHA_PLAYWRIGHT_MODULE);
const [origin, artifacts] = process.argv.slice(2);
const browser = await chromium.launch({headless:true, executablePath:process.env.KACHA_CHROMIUM_EXECUTABLE || undefined});
const checks=[]; const errors=[];
fs.mkdirSync(artifacts,{recursive:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));
 const requests=[];let unblock;let delay=false;
 const status = root => ({projectId:'工作项目',projectRoot:root,task:'source_edit',lifecycle:{status:'active'},runtime:{current:{productionReady:true},locked:{}},input:{identityStatus:'pass'},intelligenceV6:{required:true},milestones:[],stages:[],nextAction:{id:'continue',state:'ready',summary:'继续当前项目'}});
 await page.route('**/api/project/**',async route=>{
  const endpoint=new URL(route.request().url()).pathname;
  const body=route.request().postDataJSON(); requests.push({endpoint,body});
  if(delay) await new Promise(resolve=>{unblock=resolve;});
  if(body.projectRoot==='/failed') return route.fulfill({status:400,json:{error:'fixture: 项目读取失败'}});
  if(endpoint.endsWith('/observe')) return route.fulfill({json:{projectId:'进度项目',progress:{complete:2,total:13},jobs:[],warnings:[],evidenceBoundary:'观察不授予执行许可'}});
  return route.fulfill({json:status(body.projectRoot)});
 });
 await page.route('**/api/flight?*',route=>route.fulfill({json:{events:[],counts:{}}}));
 // New-project source/preflight replies must still describe the current form.
 let releaseProbe;let releaseValidation;
 await page.route('**/api/probe-video',async route=>{
  const videoPath=route.request().postDataJSON().videoPath;
  await new Promise(resolve=>{releaseProbe=resolve;});
  await route.fulfill({json:{status:'pass',media:{path:videoPath,fileName:videoPath.split('/').pop(),width:320,height:180,fps:30,durationSeconds:4,videoCodec:'h264'}}});
 });
 await page.route('**/api/preview-request',async route=>{
  await new Promise(resolve=>{releaseValidation=resolve;});
  await route.fulfill({json:{status:'pass',brief:{style:{captionFontEvidence:{resolvedFamily:'fixture'}}},readiness:{effectsResolved:0}}});
 });
 await page.goto(`${origin}/`);
 await page.locator('#styleList button').first().waitFor();
 await page.locator('#videoPath').fill('/a.mp4');await page.locator('#probeVideo').click();
 while(!releaseProbe) await new Promise(r=>setTimeout(r,10));
 await page.locator('#videoPath').fill('/b.mp4');releaseProbe();
 await page.waitForLoadState('networkidle');
 assert.notEqual(await page.locator('#sourceState').textContent(),'已读取');
 releaseProbe=null;await page.locator('#probeVideo').click();
 while(!releaseProbe) await new Promise(r=>setTimeout(r,10));releaseProbe();
 await page.waitForFunction(()=>document.querySelector('#sourceState').textContent==='已读取');
 await page.locator('#validateProject').click();
 while(!releaseValidation) await new Promise(r=>setTimeout(r,10));
 await page.locator('#notes').fill('changed while validating');releaseValidation();
 await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('配置已变化'));
 assert.equal(await page.locator('#preflightPanel').isHidden(),true);
 assert.match(await page.locator('#toast').textContent(),/配置已变化/);
 checks.push('new-project-stale-source-and-preflight-replies-rejected');
 await page.route('**/api/compile',route=>route.fulfill({json:{status:'pass',projectDirectory:'/generated-current'}}));
 releaseValidation=null;await page.locator('#validateProject').click();
 while(!releaseValidation) await new Promise(r=>setTimeout(r,10));
 const staleValidation=releaseValidation;releaseValidation=null;
 await page.locator('#generateProject').click();
 while(!releaseValidation) await new Promise(r=>setTimeout(r,10));
 assert.equal(await page.locator('main').evaluate(node=>node.inert),true);
 releaseValidation();
 await page.locator('#resultPanel:not([hidden])').waitFor();
 const staleResponse=page.waitForResponse('**/api/preview-request');staleValidation();
 await (await staleResponse).finished();
 await page.waitForLoadState('networkidle');
 assert.equal(await page.locator('#resultPanel').isVisible(),true);
 assert.equal(await page.locator('#resultPath').textContent(),'/generated-current');
 assert.equal(await page.locator('main').evaluate(node=>node.inert),false);
 checks.push('old-validation-cannot-clear-newly-generated-project');
 await page.goto(`${origin}/project`);
 await page.locator('#loadProject').click();
 assert.match(await page.locator('#loadStatus').textContent(),/绝对路径/);
 await page.locator('#projectRoot').fill('/project-a');
 delay=true;
 await page.locator('#loadProject').click();
 await page.waitForFunction(()=>document.querySelector('#projectRoot').disabled);
 assert.equal(await page.locator('#observeProject').isDisabled(),true);
 while(!unblock) await new Promise(r=>setTimeout(r,10));
 delay=false;unblock();
 await page.waitForFunction(()=>!document.querySelector('#runProject').disabled);
 const checkbox=await page.locator('#includeRender').boundingBox();assert.equal(checkbox.width,18);assert.equal(checkbox.height,18);
 await page.locator('#runProject').click();
 await page.waitForFunction(()=>!document.querySelector('#runProject').disabled);
 assert.equal(requests.find(r=>r.endpoint.endsWith('/run')).body.projectRoot,'/project-a');
 await page.locator('#projectRoot').fill('/project-b');
 assert.equal(await page.locator('#projectShell').isHidden(),true);
 assert.equal(await page.locator('#runProject').isDisabled(),true);
 checks.push('verified-target-binding-inflight-lock-and-path-invalidation');
 await page.locator('#observeProject').click();
 await page.locator('#observationCard:not([hidden])').waitFor();
 assert.equal(await page.locator('#runProject').isDisabled(),true);
 assert.match(await page.locator('#loadStatus').textContent(),/核验并读取/);
 checks.push('observation-cannot-enable-execution');
 await page.locator('#projectRoot').fill('/failed');await page.locator('#loadProject').click();
 await page.waitForFunction(()=>document.querySelector('#loadStatus').textContent.includes('fixture'));
 assert.equal(await page.locator('#projectShell').isHidden(),true);
 assert.equal(await page.locator('#runProject').isDisabled(),true);
 checks.push('failed-load-clears-stale-action');
 await page.screenshot({path:path.join(artifacts,'project-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.locator('#projectRoot').fill('/very-long-project-path/'.repeat(12));await page.locator('#observeProject').click();
 await page.locator('#observationCard:not([hidden])').waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:path.join(artifacts,'project-mobile.png'),fullPage:true});
 checks.push('390px-layout-checkbox-and-long-path');
 await page.setViewportSize({width:1440,height:1000});
 const release={project:{id:'release-a'},summary:{passed:0,total:1,readyForApproval:false,approved:false},checks:[{id:'visual',label:'画面检查',status:'pending',evidence:[]}]};
 let releaseRequest;
 await page.route('**/api/release/**',async route=>{
  releaseRequest=route.request().postDataJSON();
  if(route.request().url().endsWith('/record')) await new Promise(resolve=>{unblock=resolve;});
  await route.fulfill({json:release});
 });
 await page.goto(`${origin}/review`);
 await page.locator('#releaseManifest').fill('/a/manifest.json');await page.locator('#openRelease').click();
 await page.locator('#releaseShell:not([hidden])').waitFor();
 await page.locator('#releaseReviewer').fill('fixture reviewer');
 unblock=null; await page.locator('#releasePass').click();
 await page.waitForFunction(()=>document.querySelector('#releaseManifest').disabled);
 assert.equal(releaseRequest.projectManifestPath,'/a/manifest.json');
 while(!unblock) await new Promise(r=>setTimeout(r,10));unblock();
 await page.waitForFunction(()=>!document.querySelector('#releaseManifest').disabled);
 await page.locator('#releaseManifest').fill('/b/manifest.json');
 assert.equal(await page.locator('#releaseShell').isHidden(),true);
 assert.equal(await page.locator('#approveRelease').isDisabled(),true);
 checks.push('release-bound-target-and-write-lock');
 assert.deepEqual(errors,[]);
 const result={status:'pass',checks,scope:'Real Chrome with controlled API responses; no production media or real approvals'};
 fs.writeFileSync(path.join(artifacts,'studio-state-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
