import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createProjectTaskRunner } from '../scripts/studio_project_tasks.mjs';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'kacha-studio-reliability-'));
const shared = await import(`data:text/javascript;base64,${fs.readFileSync(new URL('../studio/shared.js', import.meta.url)).toString('base64')}`);
const checked = [];
try {
  const project = path.join(root, 'project'); fs.mkdirSync(path.join(project, '.kacha'), { recursive: true });
  fs.writeFileSync(path.join(project, '.kacha/orchestration.json'), JSON.stringify({ projectId: 'fixture', lifecycle: { status: 'draft' } }));
  const run = createProjectTaskRunner();
  const observed = await run('observe', project);
  assert.equal(observed.executionEligible, false);
  assert.equal(observed.status, 'observation_only');
  assert.throws(() => run('observe', 'relative'), /绝对路径/);
  assert.throws(() => run('unknown', project), /Unknown/);
  checked.push('real-worker-observation-and-input-boundaries');
  const worker = path.join(root, 'worker.mjs');
  fs.writeFileSync(worker, `import {parentPort,workerData} from 'node:worker_threads';
    if(workerData.options.fail) process.exit(2);
    const end=Date.now()+200;while(Date.now()<end){};
    parentPort.postMessage({value:{status:'pass',projectRoot:workerData.projectRoot}});`);
  const bounded = createProjectTaskRunner({ limit: 1, workerUrl: pathToFileURL(worker) });
  const first = bounded('status', project);
  const alias = path.join(root, 'alias'); fs.symlinkSync(project, alias, 'dir');
  assert.throws(() => bounded('run', alias), (error) => error.statusCode === 409);
  assert.throws(() => bounded('status', root), (error) => error.statusCode === 409);
  let completed = false; first.then(() => { completed = true; });
  await new Promise(resolve => setTimeout(resolve, 15));
  assert.equal(completed, false, 'main event loop remains responsive during worker CPU work');
  await first;
  await assert.rejects(bounded('status', project, { fail: true }), /异常退出/);
  await bounded('status', project);
  const media = path.join(root, 'source.mp4'); fs.writeFileSync(media, 'fixture');
  const probe = bounded('probe', media);
  assert.throws(() => bounded('compile', media), error => error.statusCode === 409);
  assert.throws(() => bounded('content-start', path.join(root, 'new-project')), error => error.statusCode === 409);
  await probe;
  const directoryAlias = path.join(root, 'root-alias'); fs.symlinkSync(root, directoryAlias, 'dir');
  const creating = bounded('content-start', path.join(root, 'new-project'));
  assert.throws(() => bounded('content-start', path.join(directoryAlias, 'new-project')), error => error.statusCode === 409);
  await creating;
  await assert.rejects(run('content-start', path.join(root, 'invalid-content'), { topic: 'test', show: 'ai-practice', style: 'xingzhe-dark-tech' }), /不匹配/);
  assert.equal(fs.existsSync(path.join(root, 'invalid-content')), false);
  const media2 = path.join(root, 'source2.mp4'); fs.writeFileSync(media2, 'fixture');
  const outputBounded = createProjectTaskRunner({ limit: 2, workerUrl: pathToFileURL(worker) });
  const mediaAlias = path.join(root, 'selected-name.mp4'); fs.symlinkSync(media, mediaAlias);
  const throughAlias = outputBounded('probe', mediaAlias);
  assert.throws(() => outputBounded('probe', media), error => error.statusCode === 409);
  assert.equal((await throughAlias).projectRoot, mediaAlias, 'execution retains the selected media path');
  const compile = outputBounded('compile', media, { outputDirectory: path.join(root, 'new-output') });
  assert.throws(() => outputBounded('compile', media2, { outputDirectory: path.join(directoryAlias, 'new-output') }), error => error.statusCode === 409);
  await outputBounded('probe', media2); // Two resource locks still occupy just one worker slot.
  await compile;
  await outputBounded('compile', media2, { outputDirectory: path.join(root, 'new-output') });
  checked.push('shared-output-alias-exclusion-and-worker-slot-accounting');
  checked.push('cross-task-capacity-media-exclusion-and-uncreated-path-aliases');
  checked.push('canonical-project-exclusion-bounded-concurrency-event-loop-and-exit-recovery');
  const originalFetch = globalThis.fetch;
  try {
    globalThis.fetch = async () => new Response('oops', {status: 503});
    await assert.rejects(shared.studioRequest('/test'), /503/);
    globalThis.fetch = async () => Response.json(null);
    await assert.rejects(shared.studioRequest('/test'), /无效数据/);
    globalThis.fetch = async () => Response.json({status:'blocked',error:'boundary'});
    assert.equal((await shared.studioRequest('/test')).status, 'blocked');
    await assert.rejects(shared.studioRequest('/test',{rejectBlocked:true}), /boundary/);
  } finally { globalThis.fetch = originalFetch; }
  checked.push('response-contract-and-explicit-blocked-policy');
  globalThis.window = new EventTarget();
  globalThis.document = new EventTarget();
  const node = new EventTarget(); let captured = null;
  node.setPointerCapture = id => { captured = id; };
  node.hasPointerCapture = id => captured === id;
  node.releasePointerCapture = () => { captured = null; };
  let moves=0,commits=0,cancels=0;
  const handlers = {move:()=>moves++,commit:()=>commits++,cancel:()=>cancels++};
  const event = (type,id) => Object.assign(new Event(type),{pointerId:id});
  assert.equal(shared.trackPointer(node,{pointerId:1,button:0},handlers),true);
  assert.equal(shared.trackPointer(node,{pointerId:2,button:0},handlers),false);
  node.dispatchEvent(event('pointermove',2));node.dispatchEvent(event('pointerup',2));
  assert.equal(moves,0);assert.equal(commits,0);
  node.dispatchEvent(event('pointermove',1));window.dispatchEvent(new Event('blur'));
  assert.equal(moves,1);assert.equal(cancels,1);assert.equal(captured,null);
  node.dispatchEvent(event('pointerup',1));assert.equal(commits,0);
  shared.trackPointer(node,{pointerId:3,button:0},handlers);
  node.dispatchEvent(event('lostpointercapture',3));assert.equal(cancels,2);
  shared.trackPointer(node,{pointerId:5,button:0},handlers);
  document.dispatchEvent(event('lostpointercapture',5));assert.equal(cancels,3);
  shared.trackPointer(node,{pointerId:4,button:0},handlers);
  node.dispatchEvent(event('pointerup',4));assert.equal(commits,1);
  checked.push('pointer-ownership-blur-capture-loss-and-next-gesture');
  console.log(JSON.stringify({status:'pass',checks:checked},null,2));
} finally { fs.rmSync(root,{recursive:true,force:true}); }
